"""empty message

Revision ID: 80376a262e33
Revises: 03f8022f40cd
Create Date: 2026-08-24 23:28:23.602456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80376a262e33'
down_revision = '03f8022f40cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
